spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/groupschannels
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

